In [1]:
import numpy as n
import keras as k

Using TensorFlow backend.


In [2]:
from sklearn.datasets import load_iris
data = load_iris()
data.target[[10, 25, 50]]
list(data.target_names[:1])

['setosa']

In [3]:
data.data[:]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [4]:
from sklearn.preprocessing import OneHotEncoder

x, y_ = data.data, data.target.reshape(-1,1)

enc = OneHotEncoder(sparse = False)
y = enc.fit_transform(y_)
y

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.

In [5]:
model = k.models.Sequential()
model.add(k.layers.Dense(16, input_shape=(4,)))
model.add(k.layers.Activation("sigmoid"))
model.add(k.layers.Dense(3))
model.add(k.layers.Activation("softmax"))
optimizer = k.optimizers.Adam(lr=0.001)
model.compile(optimizer, loss="categorical_crossentropy", metrics=["accuracy"])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                80        
_________________________________________________________________
activation_1 (Activation)    (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 51        
_________________________________________________________________
activation_2 (Activation)    (None, 3)                 0         
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________
None


In [6]:
from sklearn.model_selection import train_test_split

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2)

train_x

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 6.7,  3. ,  5. ,  1.7],
       [ 7.9,  3.8,  6.4,  2. ],
       [ 6.1,  2.9,  4.7,  1.4],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 6.4,  2.7,  5.3,  1.9],
       [ 5.4,  3.4,  1.5,  0.4],
       [ 6.8,  3. ,  5.5,  2.1],
       [ 5.8,  2.8,  5.1,  2.4],
       [ 6.2,  2.8,  4.8,  1.8],
       [ 5.5,  4.2,  1.4,  0.2],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 7.7,  2.8,  6.7,  2. ],
       [ 5.6,  3. ,  4.5,  1.5],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5. ,  2.3,  3.3,  1. ],
       [ 4.5,  2.3,  1.3,  0.3],
       [ 7.4,  2.8,  6.1,  1.9],
       [ 7.7,  2.6,  6.9,  2.3],
       [ 7.2,  3.2,  6. ,  1.8],
       [ 7.2,  3.6,  6.1,  2.5],
       [ 4.4,  3. ,  1.3,  0.2],
       [ 7.7,  3. ,  6.1,  2.3],
       [ 7.3,  2.9,  6.3,  1.8],
       [ 5.7,  3. ,  4.2,  1.2],
       [ 5.8,  2.7,  5.1,  1.9],
       [ 6.3,  3.3,  6. ,  2.5],
       [ 6.9,  3.1,  5.4,  2.1],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5

In [7]:
model.fit(train_x, train_y, epochs=100, batch_size=1, verbose=1)

Epoch 1/100
105/105 [==============================] - 1s 7ms/step - loss: 1.1359 - acc: 0.3429
Epoch 2/100
105/105 [==============================] - 0s 2ms/step - loss: 1.0279 - acc: 0.4095
Epoch 3/100
105/105 [==============================] - 0s 1ms/step - loss: 0.9615 - acc: 0.6571
Epoch 4/100
105/105 [==============================] - 0s 2ms/step - loss: 0.9009 - acc: 0.8095
Epoch 5/100
105/105 [==============================] - 0s 2ms/step - loss: 0.8505 - acc: 0.8095
Epoch 6/100
105/105 [==============================] - 0s 2ms/step - loss: 0.7985 - acc: 0.7810
Epoch 7/100
105/105 [==============================] - 0s 1ms/step - loss: 0.7495 - acc: 0.6857
Epoch 8/100
105/105 [==============================] - 0s 1ms/step - loss: 0.7064 - acc: 0.8190
Epoch 9/100
105/105 [==============================] - 0s 2ms/step - loss: 0.6680 - acc: 0.9143
Epoch 10/100
105/105 [==============================] - 0s 1ms/step - loss: 0.6361 - acc: 0.7619
Epoch 11/100
105/105 [=================

105/105 [==============================] - 0s 1ms/step - loss: 0.1150 - acc: 0.9619
Epoch 85/100
105/105 [==============================] - 0s 1ms/step - loss: 0.1113 - acc: 0.9714
Epoch 86/100
105/105 [==============================] - 0s 1ms/step - loss: 0.1098 - acc: 0.9714
Epoch 87/100
105/105 [==============================] - 0s 1ms/step - loss: 0.1094 - acc: 0.9714
Epoch 88/100
105/105 [==============================] - 0s 1ms/step - loss: 0.1061 - acc: 0.9810
Epoch 89/100
105/105 [==============================] - 0s 1ms/step - loss: 0.1060 - acc: 0.9714
Epoch 90/100
105/105 [==============================] - 0s 1ms/step - loss: 0.1084 - acc: 0.9905
Epoch 91/100
105/105 [==============================] - 0s 1ms/step - loss: 0.1061 - acc: 0.9714
Epoch 92/100
105/105 [==============================] - 0s 1ms/step - loss: 0.1034 - acc: 0.9810
Epoch 93/100
105/105 [==============================] - 0s 1ms/step - loss: 0.1013 - acc: 0.9810
Epoch 94/100
105/105 [=====================