In [1]:
import numpy as n
import keras as k

Using TensorFlow backend.


In [2]:
from sklearn.datasets import load_iris
data = load_iris()
data.target[[10, 25, 50]]
list(data.target_names[:1])

['setosa']

In [3]:
data.data[:]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [4]:
from sklearn.preprocessing import OneHotEncoder

x, y_ = data.data, data.target.reshape(-1,1)

enc = OneHotEncoder(sparse = False)
y = enc.fit_transform(y_)
y

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.

In [5]:
model = k.models.Sequential()
model.add(k.layers.Dense(16, input_shape=(4,)))
model.add(k.layers.Activation("sigmoid"))
model.add(k.layers.Dense(3))
model.add(k.layers.Activation("softmax"))
optimizer = k.optimizers.Adam(lr=0.0025)
model.compile(optimizer, loss="categorical_crossentropy", metrics=["accuracy"])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                80        
_________________________________________________________________
activation_1 (Activation)    (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 51        
_________________________________________________________________
activation_2 (Activation)    (None, 3)                 0         
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________
None


In [6]:
from sklearn.model_selection import train_test_split

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2)

train_x

array([[ 6.3,  2.3,  4.4,  1.3],
       [ 4.9,  2.5,  4.5,  1.7],
       [ 6. ,  2.7,  5.1,  1.6],
       [ 6.1,  2.8,  4.7,  1.2],
       [ 6.4,  3.2,  4.5,  1.5],
       [ 5.8,  2.6,  4. ,  1.2],
       [ 6.1,  3. ,  4.9,  1.8],
       [ 5. ,  3.3,  1.4,  0.2],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 7.1,  3. ,  5.9,  2.1],
       [ 4.6,  3.2,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 7.3,  2.9,  6.3,  1.8],
       [ 5.9,  3. ,  4.2,  1.5],
       [ 4.4,  3.2,  1.3,  0.2],
       [ 6.7,  3.3,  5.7,  2.5],
       [ 5.6,  2.5,  3.9,  1.1],
       [ 6.5,  3. ,  5.5,  1.8],
       [ 6.9,  3.1,  5.4,  2.1],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.5,  2.6,  4.4,  1.2],
       [ 5.5,  2.3,  4. ,  1.3],
       [ 6.3,  2.5,  5. ,  1.9],
       [ 7.7,  3. ,  6.1,  2.3],
       [ 4.5,  2.3,  1.3,  0.3],
       [ 6.5,  3.2,  5.1,  2. ],
       [ 4.4,  3. ,  1.3,  0.2],
       [ 6.3,  3.3,  6. ,  2.5],
       [ 7.4,  2.8,  6.1,  1.9],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 4

In [7]:
model.fit(train_x, train_y, epochs=100, batch_size=1, verbose=1)

Epoch 1/100
120/120 [==============================] - 1s 6ms/step - loss: 1.1227 - acc: 0.3500
Epoch 2/100
120/120 [==============================] - 0s 1ms/step - loss: 0.9219 - acc: 0.5250
Epoch 3/100
120/120 [==============================] - 0s 1ms/step - loss: 0.7153 - acc: 0.7333
Epoch 4/100
120/120 [==============================] - 0s 1ms/step - loss: 0.5711 - acc: 0.7667
Epoch 5/100
120/120 [==============================] - 0s 1ms/step - loss: 0.4853 - acc: 0.7917
Epoch 6/100
120/120 [==============================] - 0s 1ms/step - loss: 0.4273 - acc: 0.9167
Epoch 7/100
120/120 [==============================] - 0s 1ms/step - loss: 0.3834 - acc: 0.9333
Epoch 8/100
120/120 [==============================] - 0s 1ms/step - loss: 0.3458 - acc: 0.9500
Epoch 9/100
120/120 [==============================] - 0s 1ms/step - loss: 0.3244 - acc: 0.9833
Epoch 10/100
120/120 [==============================] - 0s 1ms/step - loss: 0.2974 - acc: 0.9500
Epoch 11/100
120/120 [=================

120/120 [==============================] - 0s 1ms/step - loss: 0.0598 - acc: 0.9833
Epoch 86/100
120/120 [==============================] - 0s 1ms/step - loss: 0.0676 - acc: 0.9750
Epoch 87/100
120/120 [==============================] - 0s 2ms/step - loss: 0.0590 - acc: 0.9750
Epoch 88/100
120/120 [==============================] - 0s 1ms/step - loss: 0.0568 - acc: 0.9750
Epoch 89/100
120/120 [==============================] - 0s 1ms/step - loss: 0.0495 - acc: 0.9917
Epoch 90/100
120/120 [==============================] - 0s 1ms/step - loss: 0.0500 - acc: 0.9833
Epoch 91/100
120/120 [==============================] - 0s 2ms/step - loss: 0.0615 - acc: 0.9833
Epoch 92/100
120/120 [==============================] - 0s 1ms/step - loss: 0.0601 - acc: 0.9833
Epoch 93/100
120/120 [==============================] - 0s 1ms/step - loss: 0.0581 - acc: 0.9833
Epoch 94/100
120/120 [==============================] - 0s 2ms/step - loss: 0.0563 - acc: 0.9833
Epoch 95/100
120/120 [=====================