In [1]:
import numpy as n
import keras as k

Using TensorFlow backend.


In [2]:
from sklearn.datasets import load_iris
data = load_iris()
data.target[[10, 25, 50]]
list(data.target_names[:1])

['setosa']

In [3]:
data.data[:]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [4]:
from sklearn.preprocessing import OneHotEncoder

x, y_ = data.data, data.target.reshape(-1,1)

enc = OneHotEncoder(sparse = False)
y = enc.fit_transform(y_)
y

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.

In [5]:
model = k.models.Sequential()
model.add(k.layers.Dense(16, input_shape=(4,)))
model.add(k.layers.Activation("sigmoid"))
model.add(k.layers.Dense(3))
model.add(k.layers.Activation("softmax"))
optimizer = k.optimizers.Adam(lr=0.001)
model.compile(optimizer, loss="categorical_crossentropy", metrics=["accuracy"])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                80        
_________________________________________________________________
activation_1 (Activation)    (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 51        
_________________________________________________________________
activation_2 (Activation)    (None, 3)                 0         
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________
None


In [6]:
from sklearn.model_selection import train_test_split

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2)

train_x

array([[ 5. ,  3.4,  1.5,  0.2],
       [ 6.7,  3. ,  5. ,  1.7],
       [ 5. ,  3.5,  1.6,  0.6],
       [ 5.7,  2.8,  4.1,  1.3],
       [ 5.9,  3. ,  5.1,  1.8],
       [ 5.1,  3.8,  1.9,  0.4],
       [ 5. ,  3.5,  1.3,  0.3],
       [ 6.4,  2.8,  5.6,  2.1],
       [ 7.3,  2.9,  6.3,  1.8],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.5,  2.4,  3.7,  1. ],
       [ 6.7,  3.1,  4.7,  1.5],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 7.4,  2.8,  6.1,  1.9],
       [ 6.2,  2.8,  4.8,  1.8],
       [ 5.6,  2.8,  4.9,  2. ],
       [ 4.8,  3.1,  1.6,  0.2],
       [ 6.1,  2.8,  4. ,  1.3],
       [ 6.1,  3. ,  4.6,  1.4],
       [ 6.2,  2.9,  4.3,  1.3],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 6.4,  3.2,  5.3,  2.3],
       [ 6.7,  2.5,  5.8,  1.8],
       [ 5.4,  3. ,  4.5,  1.5],
       [ 7.7,  3.8,  6.7,  2.2],
       [ 6.4,  2.9,  4.3,  1.3],
       [ 6.3,  3.3,  6. ,  2.5],
       [ 6.2,  2.2,  4.5,  1.5],
       [ 5.8,  2.7,  5.1,  1.9],
       [ 6

In [7]:
model.fit(train_x, train_y, epochs=100, batch_size=1, verbose=1)

Epoch 1/100
120/120 [==============================] - 0s 3ms/step - loss: 1.0206 - acc: 0.5250
Epoch 2/100
120/120 [==============================] - 0s 1ms/step - loss: 0.9375 - acc: 0.5917
Epoch 3/100
120/120 [==============================] - 0s 1ms/step - loss: 0.8649 - acc: 0.6750
Epoch 4/100
120/120 [==============================] - 0s 1ms/step - loss: 0.7988 - acc: 0.6917
Epoch 5/100
120/120 [==============================] - 0s 1ms/step - loss: 0.7405 - acc: 0.6917
Epoch 6/100
120/120 [==============================] - 0s 1ms/step - loss: 0.6962 - acc: 0.7167
Epoch 7/100
120/120 [==============================] - 0s 1ms/step - loss: 0.6541 - acc: 0.6917
Epoch 8/100
120/120 [==============================] - 0s 1ms/step - loss: 0.6212 - acc: 0.7250
Epoch 9/100
120/120 [==============================] - 0s 1ms/step - loss: 0.5890 - acc: 0.6917
Epoch 10/100
120/120 [==============================] - 0s 1ms/step - loss: 0.5665 - acc: 0.7750
Epoch 11/100
120/120 [=================

120/120 [==============================] - 0s 1ms/step - loss: 0.1023 - acc: 0.9750
Epoch 86/100
120/120 [==============================] - 0s 1ms/step - loss: 0.1018 - acc: 0.9750
Epoch 87/100
120/120 [==============================] - 0s 1ms/step - loss: 0.1030 - acc: 0.9833
Epoch 88/100
120/120 [==============================] - 0s 1ms/step - loss: 0.1015 - acc: 0.9750
Epoch 89/100
120/120 [==============================] - 0s 1ms/step - loss: 0.1029 - acc: 0.9750
Epoch 90/100
120/120 [==============================] - 0s 1ms/step - loss: 0.1009 - acc: 0.9750
Epoch 91/100
120/120 [==============================] - 0s 1ms/step - loss: 0.0965 - acc: 0.9750
Epoch 92/100
120/120 [==============================] - 0s 1ms/step - loss: 0.0965 - acc: 0.9750
Epoch 93/100
120/120 [==============================] - 0s 1ms/step - loss: 0.0957 - acc: 0.9750
Epoch 94/100
120/120 [==============================] - 0s 1ms/step - loss: 0.0939 - acc: 0.9750
Epoch 95/100
120/120 [=====================

In [10]:
# Evaluate the model using the test data set.
loss, accuracy = model.evaluate(test_x, test_y, verbose=0)

# Output the accuracy of the model.
print("\n\nLoss: %6.4f\tAccuracy: %6.4f" % (loss, accuracy))



Loss: 0.0537	Accuracy: 1.0000
